apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azurepipelinespools.dev.azure.com
  namespace: azuredevops
spec:
  group: dev.azure.com
  names:
    kind: AzurePipelinesPool
    listKind: AzurePipelinesPoolList
    plural: azurepipelinespools
    singular: azurepipelinespool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AzurePipelinesPool is the Schema for the azurepipelinespools API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AzurePipelinesPoolSpec defines the desired state of AzurePipelinesPool
          type: object
          properties:
            controllerImage:
              type: string
            buildkitReplicas:
              type: integer
              minimum: 0
            agentPools:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  spec:
                    type: object
                required: ["name", "spec"]
          required: ["controllerImage", "buildkitReplicas", "agentPools"]
        status:
          description: AzurePipelinesPoolStatus defines the observed state of AzurePipelinesPool
          type: object
      type: object
      required: ["spec"]
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
